//--

localizationModule.constant('DanceDictionary', {
  toEnglish: {
        'Регистрация закрыта':'Registration is closed',
        'Зарегистрировать ещё группы':'Register another competitions',
        'Регистрация выполнена.': 'Registration is complete.',
        'Регистрация не выполнена.': 'Registration failed.',
        'Обнаружены конфликтные группы для участника' : 'Found conflicting competitions for participant',
        'Место проведения':'Location',
        
        'Размер страницы':'Page size',
        'Поиск в столбце': 'Search in column',
        'Все группы': 'All competitions',
        'Внимание!': 'Attention!',
        'Готово!': 'Done!',
        'Язык системы' : 'System language',
        'd MMMM y'     : 'MMMM d, y',
        'В списке не отображены группы, в которых данная пара уже зарегистрирована.' : 'The competitions with the already registered couple are not displayed in the list.',
        'Ваш email' : 'Your email',
        'Ваше имя' : 'Your name',
        'Веб-сайт организатора' : 'Organizer web-site',
        'Возрастная группа' : 'Age group',
        'Возрастные группы' : 'Age groups',
        'Время' : 'Time',
        'Все дни' : 'All days',
        'Всего групп' : 'Total competitions',
        'Всего участников / уникальных' : 'Total participants / unique',
        'Вход' : 'Login',
        'Выберите группы!' : 'Select competitions!',
        'Выберите турнир для отображения подробной информации.' : 'Select a tournament to show detailed information.',
        'Выбрано' : 'Selected',
        'Главный тренер' : 'Main trainer',
        'Город' : 'City',
        'Город, Страна' : 'City, Country',
        'групп из' : 'competitions from',
        'Группы' : 'Competitions',
        'Группы пары' : 'Couple competitions',
        'Группы участника' : 'Participant competitions',
        'Далее' : 'Next',
        'Дата' : 'Date',
        'Дата начала / окончания' : 'Start date / end date',
        'Дата начала' : 'Start date',
        'Дата окончания' : 'End date',
        'Дата рождения' : 'Date of birth',
        'Детально' : 'Details',
        'Программа' : 'Discipline',
        'Для просмотра списка всех групп турнира нажмите на ссылку (») в колонке "Группы" или выберите внизу вкладку "Группы(N)".' : 'To see the list of all tournament competitions, click the link (») in "Competitions" column, or select "Competitions (N)" tab at the bottom.',
        'Для просмотра списка всех участников турнира нажмите на ссылку (») в колонке "Участники".' : 'To see the list of all tournament participants, click the link (») in the "Participants" column.',
        'Для просмотра списка участников группы нажмите на ссылку (») в колонке "Участники".' : 'To see a list of group\'s participants, click the link (») in "Participants" column.',
        'Для регистрации в \"соло\" заполните только одно поле.' : 'To register for the \"solo\" fill in only one field.',
        'Для регистрации в турнире нажмите на ссылку (») в колонке "Регистрация".' : 'To register for the tournament, click the link (») in "Registration" column.',
        'Для регистрации в \"соло\" нажмите на переключатель.' : 'To register for the \"solo\" click the checkbox.',
        'Добавить' : 'Add',
        'Дополнительная информация' : 'Other information',
        'Другие тренеры' : 'Other trainers',
        'Женский' : 'Female',
        'Зарегистрировать' : 'Register',
        'Идет загрузка групп...' : 'Loading competitions ...',
        'Идет загрузка данных...' : 'Loading data ...',
        'из' : 'of',
        'Изменить' : 'Edit',
        'Импорт' : 'Import',
        'Имя' : 'Name',
        'Информация' : 'Information',
        'Класс' : 'Class',
        'Классы' : 'Classes',
        'Клуб / Город' : 'Club / City',
        'Клуб' : 'Club',
        'Конфликтные группы для ' : 'Conflicting competitions for ',
        'Конфликтные группы участника - это группы из других турниров, в которых зарегистрирован участник. Дата конфликтной группы совпадает с одной из дат групп выбранного турнира (заголовок сверху). Публикация списка конфликтных групп предназначена лишь для информирования участников.' : 'Conflicting participant competitions are the competitions of other tournaments where the participant is registered. Conflict competition date coincides with one of the competitions dates of the selected tournament (title above). Publication of a list of conflict competitions is intended only to inform the participants.',
        'Коротко' : 'Short',
        'Ла: ' : 'La:',
        'Мужской' : 'Male',
        'Нажмите на ссылку в колонке "Группы" для просмотра списка групп турнира, в которых зарегистрирована пара (участник).' : 'Click the link in "Competitions" column  to see a list of the tournament where the couple (participant) is registered.',
        'Назад' : 'Back',
        'Название' : 'Name',
        'Нашли ошибку в работе системы? Что-то не нравится? Пожалуйста, напишите нам Ваши замечания и предложения.' : 'Found a bug in the system? Don\'t like something? Please write us your comments and suggestions.',
        'Не оплачено' : 'Not paid',
        'Нет доступных групп.' : 'No available competitions.',
        'Номер WDSF' : 'Number WDSF',
        'Номер партнера' : 'Male number',
        'Номер партнерши' : 'Female number',
        'Номер ФТСАРР' : 'Number RFDARR',
        'Номера классификационных книжек WDSF' : 'Numbers of WDSF classification books',
        'Номера классификационных книжек ФТСАРР' : 'Numbers of RFDARR classification books',
        'Обратная связь' : 'Feedback',
        'Оплатить на danceplat.ru' : 'Pay on danceplat.ru',
        'Организатор' : 'Organizer',
        'Открыть для просмотра' : 'Open to view',
        'Открыть список групп' : 'Show a list of competitions',
        'Открыть список групп, в которых зарегистрирована пара' : 'Show a list of competitions that the couple is registered in',
        'Открыть список участников' : 'Show a list of participants',
        'Открыть список участников группы' : 'Show a list of competition participants',
        'Отмена' : 'Cancel',
        'Отображать дополнительные столбцы' : 'Display additional columns',
        'Отправить' : 'Send',
        'Оформить »' : 'Check in »',
        'Оформить регистрацию' : 'Click for "Check in"',
        'Очистить' : 'Clear',
        'Пара' : 'Couple',
        'Партнер / Партнерша' : 'Male / Female',
        'Партнер' : 'Male partner',
        'Партнерша' : 'Female partner',
        'Первая страница' : 'First page',
        'Перейти к списку групп пары / участника (' : 'Go to the competitions list of couples / participants (',
        'Подтверждение регистрационных данных' : 'Confirmation of registration data',
        'Поиск' : 'Search',
        'Пол' : 'Gender',
        'Поля отмеченные * обязательны для заполнения.' : 'Fields marked with an asterisk (*) are required.',
        'После завершения регистрации произойдет передача данных в danceplat.ru, по прошествии некоторого времени после завершения оплаты ваши данные отобразятся в регистрационных списках.' : 'After completing the registration, data will be sent to danceplat.ru, after some time when your payment is confirmed your data will be shown in the registration lists.',
        'После завершения регистрации произойдет переход на страницу с группами пары, там вы сможете выбрать необходимые группы и перейти к оплате.' : 'After registration you will be redirected to the page of couple competitions, there you can choose the required competitions and proceed to payment.',
        'Последняя страница' : 'Last page',
        'Предыдущая страница' : 'Previous page',
        'Ранг' : 'Rank',
        'Регистрация' : 'Registration',
        'Регистрация WDSF' : 'Registration for WDSF',
        'Регистрация других участников' : 'Registration for other participants',
        'Регистрация осуществляется по WDSF номерам. Поиск участников идет по базе данных "World DanceSport Federation".' : 'Registration is carried by WDSF numbers. Find participants is the database "World DanceSport Federation".',
        'Регистрация осуществляется по номерам классификационных книжек и на основании информации Базы данных спортсменов "ФТСАРР" на момент регистрации.' : 'Registration is carried by numbers and classification of books based on the information Databases athletes "RFDARR" at the time of registration.',
        'Регистрация ФТСАРР' : 'Registration for RFDARR',
        'Регистрация участников »' : 'Registration of participants »',
        'Регистрация участников на турнир' : 'Registration of participants at the tournament',
        'Регистрация участников по WDSF номерам' : 'Registration of participants at WDSF numbers',
        'Регистрация участников по ФТСАРР номерам' : 'Registration of participants at RFDARR numbers',
        'Режим' : 'Mode',
        'Система регистрации' : 'Registration system',
        'Скрывать дополнительные столбцы' : 'Hide additional columns',
        'Следующая страника' : 'Next page',
        'Соло' : 'Solo',
        'Сообщение' : 'Message',
        'Список всех групп турнира' : 'List of all competitions of the tournament',
        'Список всех уникальных участников турнира' : 'List of all unique participants of the tournament',
        'Список всех участников »' : 'List of all participants »',
        'Справочники' : 'Directories',
        'Ст: ' : 'St:',
        'Статус' : 'Status',
        'Страна' : 'Country',
        'Страница' : 'Page',
        'Тема сообщения' : 'Subject',
        'Тип' : 'Type',
        'Тренер #1. Фамилия, Имя' : 'Trainer #1. Full name',
        'Тренер #2. Фамилия, Имя' : 'Trainer #2. Full name',
        'Тренер(ы)' : 'Trainers',
        'Тренеры' : 'Trainers',
        'Турнир' : 'Tournament',
        'Турниры' : 'Tournaments',
        'Удалить' : 'Remove',
        'Участник' : 'Participant',
        'Участники' : 'Participants',
        'Участники ФТСАРР' : 'RFDARR Participants',
        'Фамилия' : 'Last name',
        'Фамилия, Имя' : 'Full name',
        'Фильтр: Ранг турнира' : 'Filter: Rank of tournament',
        'Фильтр: Статус турнира' : 'Filter: Status of tournament',
        'Форма обратной связи' : 'Feedback form',
        'Цена' : 'Price',
        'руб.' : 'rub.',
        'Щелчком мыши выберите группы, в которые необходимо зарегистрировать пару.' : 'Click to select the competitions to which you must register coulpe.',
        'Щелчком мыши выберите необходимые группы для передачи данных в платежную систему.' : 'Click to select the desired competitions for data transmission to the payment system.',
        'Язык' : 'Lang',
        
        ' - участие в группе не оплачено.' : ' - participation in the competition is not paid.',
        ' - участие в группе отменено.' : ' - participation in the group canceled.',
        'Cписок всех групп »' : 'List of all competitions »',
        'Выберите год и турнир. Ярким синим цветом выделены группы, которые уже есть базе данных. Сравнение идет по IdInternal. Красным выделены группы с ошибками, их можно исправить.' : 'Select the year and tournament. Competitions that already have a database are highlighted in bright blue. Comparison is on IdInternal. Competitions with errors are highlighted in red and can be corrected.',
        'Выход' : 'LogOut',
        'Год' : 'Year',
        'Группы, доступные для импорта' : 'Competitions, available for import',
        'Доступные для импорта турниры' : 'Tournaments, available for import',
        'Заголовок' : 'Title',
        'Загрузка групп в турнир' : 'Import competitions into tournament',
        'Макс.' : 'Limit',
        'Международный' : 'International',
        'Нажмите на ссылку (») в колонке "Группы" для просмотра списка групп турнира, в которых зарегистрирована пара (участник).' : 'Click the link (») in "Competitions" column  to see a list of the tournament where the couple (participant) is registered.',
        'Партнер / партнерша' : 'Male / Female',
        'Показать ошибки' : 'Show errors',
        'Лимит' : 'Limit',
        'Просмотр формы' : 'View form',
        'Редактирование группы' : 'Competition editing',
        'Редактирование турнира' : 'Tournament editing',
        'Серый цвет' : 'Grey color',
        'Сохранить' : 'Save',
        'Участники группы' : 'Competition participants',
        'Хеш' : 'Hash',
        'ЧЧ:ММ' : 'HH:MM',
        'Ярким цветом выделены турниры, которые уже есть базе данных. Сравнение идет по IdInternal. Для сохранения турнира заполните все дополнительные поля в диалоговом окне импорта.' : 'Tournaments that are already in the database are highlighted in bright color. Comparison is on IdInternal. To save the tournament fill in all additional fields in the import dialog box.',
        
        'Доступные группы для регистрации.' : 'Available competitions for registration',
        'Выбрано %1 из %2.' : 'Selected %1 from %2.',
        'Чтобы разблокировать вкладку нажмите ″Назад″' : 'To unlock the tab, click on "Back"',
        
        'Заполните / измените остальные поля.':'Fill or modify the other fields.',
        'Вернуться назад' : 'Go back',
        'Данные для передачи в платежную систему' : 'Data for transmission to the payment system',
        'На главную' : 'To home page',
        'Передать данные' : 'Transfer data',
        
        'Оставьте свои отзывы, предложения, замечания!':'Give us your feedback, suggestions, comments!',
        'Регистрация участников невозможна! Статус турнира - "': 'Registration of participants cannot be done! Tournament status - ',
        'Группы турнира': 'Competitions of the tournament',
        'Часть данных получена от WDSF.' : 'Part of data received from WDSF.',
        'Оплачено': 'Paid',
        'Черный цвет - участие в группе оплачено.' : 'Black color - participation in the competition has been paid.',
        'Уникальные участники турнира, всего ':'Unique participants in the tournament, total count ',
        'Регистрация прошла успешно, на данной странице отображены все группы пары/участника в турнире.': 'Registration was successfully completed. This page displays couple/participant competitions in the tournament.',
        'Загрузить' : 'Upload',
        'Обзор' : 'Browse',
        'Выберите файл' : 'Select file',
        'Статистика' : 'Statistics',
        'Спортсменов в БД' : 'Total count athletes in database',
        'Спортсменов ФТСАРР в БД' : 'Total count RFDARR athletes in database',
        'Спортсменов WDSF в БД' : 'Total count WDSF athletes in database',
        'Других спортсменов в БД' : 'Total count other athletes in database',
        'Последнее обновление спортсменов ФТСАРР было' : 'RFDARR athletes last updated',
        'Доступен ФТСАРР':'Available for RFDARR',
        'Доступен WDSF':'Available for WDSF',
        'Доступен другим':'Available for others',
        
        /* 11 oct*/
        'Поиск регистрации' : 'Search registration',
        'Группа в турнире' : 'Competition',
        'Все группы •' : 'All competitions •',
        'Все группы »' : 'All competitions »',
        'Регистрация »' : 'Registration »',
        'Все участники »' : 'All participants »',
        'Все участники •' : 'All participants •',
        'Сейчас Вы на этой странице' : 'You are currently on this page',
        'Регистрация •' : 'Registration •',
        'Результаты регистрации' : 'Registration results',
        'Перейти к списку групп пары / участника для оплаты (' : 'Go to the list of competitions (couple / participant) for payment (',
        'Информация о регистрации в группу' : 'Information on registration in competition',
        'После завершения регистрации перейдите на страницу с группами пары / участника, там вы сможете выбрать необходимые группы и передать данные в платежную систему.' : 'Once registration is complete, go to the page with competitions of couples / participant, where you can select the required competitions and transmit data to the billing system.',
        'Статус пары' : 'Couple status',
        'Возрастная группа пары' : 'Couple age group',
        'Участники группы •' : 'Participants of competition •',
        'Группы участника •' : 'Competitions of participant •',
        'Группы пары •' : 'Competitions of couple •',
        'участника' : 'participant',
        'пары' : 'couple',
        'ФТСАРР' : 'RFDARR',
        'Перейти' : 'Watch',
        'Фамилия спортсмена' : 'Last name',
        'Вы можете найти все группы, в которых зарегистрирован спортсмен. Поиск по всем турнирам.' : 'You can find all competitions in which the registered athlete. Search All tournaments.',
        'Группы, в которых зарегистрирован спортсмен' : 'Competitions in which the registered athlete',
        'Импортировать' : 'Import',
        'Импортировать доступные' : 'Import available items',
        'Ссылка на источник данных:' : 'Link to source of data',
        'Группа' : 'Competition',
        'Возр. гр.' : 'Age group',
        'Выберите дату для активации переключателя' : 'Select date for activate switcher',
        'Дисциплина' : 'Discipline',
        'Соответствующая группа WDSF' : 'Competition WDSF',
        
        ' - участие не оплачено.' : ' - participation is not paid.',
        ' - участие отменено.' : ' - participation is canceled.',
        'Оплачены' : 'Paid',
        'd MMMM' : 'd MMMM',
        'WDSF Controller' : 'WDSF Controller',
        'Возр. группа' : 'Age group',
        'Выберите организатора для доступа к регистрации:' : 'Select an organizer for access to registration:',
        'Группы »' : 'Competitions »',
        'Группы •' : 'Competitions •',
        'Код доступа не найден, переход на страницу для регистрации невозможен.' : 'The access code is not found, a transition to the page for registration is impossible.',
        'Количество оплативших участников' : 'Number of paid participants',
        'Количество оплаченных групп' : 'Number of paid competitions',
        'Нет данных.' : 'No data.',
        'Поиск регистрации участника по фамилии!' : 'Searching registration of athlete by surname',
        'Список всех участников турнира' : 'List of participants of the tournament',
        'Уникальные участники турнира' : 'Unique participants of the tournament',
        'Участники »' : 'Participants »',
        'Участники •' : 'Participants •',
        'Экспорт участников »' : 'Export participants',
        'Всего участников':'Number of participants',
        'уникальных':'unique',
        'Всего': 'Total count',
        
        'Задать вопрос' : 'Ask a question',
        'Инструкция к регистрации' : 'Instructions for registration',
        'Информация о турнире' : 'Tournament info',
        'Информация »' : 'Information »',
        'Перейдите по ссылке для получения подробной информации' : 'Click here for more information',
        'ВАЖНОЕ ОБЪЯВЛЕНИЕ' : 'Important announcement',
        'Зарегистрировать ещё участников »' : 'Register more participants »',
        'Введите номера классификационных книжек ФТСАРР' : 'Enter the number of RFDARR classification books',
        'Введите номера классификационных книжек WDSF' : 'Enter the number of WDSF classification books',
        'Регистрация осуществляется по MIN номерам WDSF. Поиск участников идет по базе данных "World DanceSport Federation".' : 'Registration is performed by MIN numbers WDSF. Search participants in the database of "World DanceSport Federation".',
        'Тренер. Фамилия, Имя' : 'Trainer. Full name',
        'Оплачено участников' : 'Paid participants',
        'Регистрация в турнир завершена. Все платежи запрещены.' : 'Registration in the tournament is completed. All payments are prohibited.',
        'Для всех номинаций кроме \"соло\", стоимость участия указана для пары участников.' : 'For all nominations except \"solo\", the price of participation is for couple of participants.',
        'Для всех номинаций стоимость участия указана для пары участников.' : 'For all competitions price is for couple of participants.',
        'Доступные группы.' : 'Available competitions.',
        'Доп. поля можно не заполнять.' : 'Other fields may be empty.',
        '-- Вкладка по умолчанию --' : '-- Default tab page --',
        'Другие' : 'Others',
        '-- Язык по умолчанию --' : '-- Default language --',
        'Количество доступных мест' : 'The number of tickets available for the participants',
        'Для некоторых групп могут быть введены ограничения. "Доступно мест" это "Лимит" минус "Количество проданных билетов".' : 'Some competition may be restrictions. "Available" this "Limit" minus "Number of tickets sold."',
        'Группы, в которых не осталось мест(0) закрыты для регистрации и продажи билетов.' : 'Competitions in which there is no available tickets (0) closed to registration and ticket sales.',
        'Осталось мест' : 'Available',
        'Перейти на сайт ФТСАРР' : 'Go to RFDARR site',
        'Регистрация осуществляется по номерам классификационных книжек и на основании информации' : 'Registration is carried by numbers and classification of books based on the information',
        'Базы данных спортсменов "ФТСАРР"' : 'Databases athletes "RFDARR"',
        'на момент регистрации.' : 'at the time of registration.',
        'Выберите номинации' : 'Select competitions',
        'Класс ST, LA' : 'ST, LA class',
        'Оплата отключена' : 'Payment is disabled',
        'Все классы' : 'All classes'



 

  },
  toRussian: {
  },
  toDeutsch: {
        'Оплата отключена' : 'Die Zahlung ist deaktiviert',
        'Зарегистрировать ещё группы': 'Registrieren Mehr Gruppe',
        'Регистрация выполнена.': 'Die Registrierung ist abgeschlossen.',
        'Регистрация не выполнена.': 'Registrierung fehlgeschlagen.',
        'Обнаружены конфликтные группы для участника' : 'Gefunden Konfliktgruppen zu feiern',
        'Место проведения':'Austragungsort',
      
        ' - участие в группе не оплачено.' : ' - teilnahme an der gruppe ist nicht bezahlt.',
        ' - участие в группе отменено.'    : ' - teilnahme an der gruppe abgebrochen.',
        'Cписок всех групп »' : 'Liste aller gruppen »',
        'd MMMM y'            : 'd MMMM y',
        'В списке не отображены группы, в которых данная пара уже зарегистрирована.' : 'Die liste wird nicht angezeigt, gruppen, in denen dieses paar bereits registriert ist.',
        'Ваш email' : 'Ihre E-Mail',
        'Ваше имя' : 'Ihr Name',
        'Веб-сайт организатора' : 'Webseite veranstalter',
        'Вернуться назад' : 'Zurück',
        'Внимание!': 'Achtung!',
        'Возрастная группа' : 'Altersgruppe',
        'Возрастные группы' : 'Altersgruppen',
        'Время' : 'Zeit',
        'Все группы': 'Alle gruppen',
        'Все дни' : 'Alle tage',
        'Всего групп' : 'Insgesamt gruppen',
        'Всего участников / уникальных' : 'Anzahl der teilnehmer / unique',
        'Вход' : 'Eingang',
        'Выберите год и турнир. Ярким синим цветом выделены группы, которые уже есть базе данных. Сравнение идет по IdInternal. Красным выделены группы с ошибками, их можно исправить.' : 'Wählen Sie jahr und das turnier. Helles Blau hervorgehoben gruppen, die bereits über eine datenbank. Der vergleich ist auf IdInternal. In der roten gruppe mit fehlern hervorgehoben korrigiert werden.',
        'Выберите группы!' : 'Wählen sie die gruppe!',
        'Выберите турнир для отображения подробной информации.' : 'Wählen sie ein turnier, um detaillierte informationen anzuzeigen.',
        'Выберите файл' : 'Wählen sie die datei',
        'Выбрано %1 из %2.' : 'Registriert %1 / %2.',
        'Выбрано' : 'Registriert',
        'Выход' : 'Beenden',
        'Главный тренер' : 'Head coach',
        'Год' : 'Jahr',
        'Город' : 'Stadt',
        'Город, Страна' : 'Stadt, Land',
        'Готово!': 'Fertig!',
        'групп из' : 'gruppen von',
        'Группы' : 'Gruppen',
        'Группы пары' : 'Gruppen paare',
        'Группы турнира': 'Gruppen turnier',
        'Группы участника' : 'Benutzergruppen',
        'Группы, доступные для импорта' : 'Gruppen für den import verfügbar',
        'Далее' : 'Weiter',
        'Данные для передачи в платежную систему' : 'Daten zur Übertragung zu dem abrechnungssyste',
        'Дата' : 'Datum',
        'Дата начала / окончания' : 'Datum von start / ende',
        'Дата начала' : 'Startdatum',
        'Дата окончания' : 'Verfallsdatum',
        'Дата рождения' : 'Geburtsdatum',
        'Детально' : 'In details',
        'Для просмотра списка всех групп турнира нажмите на ссылку (») в колонке "Группы" или выберите внизу вкладку "Группы(N)".' : 'Um eine liste mit allen gruppen des turniers zu sehen, klicken sie auf den link (») in der spalte "Gruppen" reiter an der unterseite, oder wählen sie "Gruppe (N)".',
        'Для просмотра списка всех участников турнира нажмите на ссылку (») в колонке "Участники".' : 'Um eine liste aller spieler im turnier zu sehen, klicken Sie auf den link (») in der spalte "Mitglieder."',
        'Для просмотра списка участников группы нажмите на ссылку (») в колонке "Участники".' : 'Um eine liste der gruppen anzuzeigen, klicken sie auf den Link (») in der spalte "Mitglieder".',
        'Для регистрации в \"соло\" заполните только одно поле.' : 'Um sich für den \"solo\" registrieren füllen sie nur ein feld.',
        'Для регистрации в \"соло\" нажмите на переключатель.' : 'Um sich für den \"solo\" drücken sie den Schalter registrieren.',
        'Для регистрации в турнире нажмите на ссылку (») в колонке "Регистрация".' : 'Um sich für das turnier zu registrieren, klicken sie auf den link (») in der spalte "Datum".',
        'Добавить' : 'Hinzufügen',
        'Дополнительная информация' : 'Zusätzliche informationen',
        'Доступные группы для регистрации.' : 'Verfügbar für gruppenanmeldungen.',
        'Доступные для импорта турниры' : 'Verfügbar für import-turniere',
        'Другие тренеры' : 'Andere trainer',
        'Других спортсменов в БД' : 'Andere athleten in der datenbank',
        'Женский' : 'Weiblich',
        'Заголовок' : 'Kopfzeile',
        'Загрузить' : 'Herunterladen',
        'Загрузка групп в турнир' : 'Download-gruppen im turnier',
        'Заполните / измените остальные поля.':'Füllen / ändern sie die anderen felder.',
        'Зарегистрировать' : 'Buch',
        'Идет загрузка групп...' : 'Lädt gruppen...',
        'Идет загрузка данных...' : 'Daten werden geladen...',
        'из' : 'von',
        'Изменить' : 'ändern',
        'Импорт' : 'Importe',
        'Имя' : 'Name',
        'Информация' : 'Information',
        'Класс' : 'Klasse',
        'Классы' : 'Klassen',
        'Клуб / Город' : 'Verein / Stadt',
        'Клуб' : 'Verein',
        'Конфликтные группы для ' : 'Widersprüchliche gruppen',
        'Конфликтные группы участника - это группы из других турниров, в которых зарегистрирован участник. Дата конфликтной группы совпадает с одной из дат групп выбранного турнира(заголовок сверху). Публикация списка конфликтных групп предназначена лишь для информирования участников.' : 'Widersprüchliche Benutzergruppen - diese Gruppe von anderen Turnieren, in denen die Teilnehmer registriert ist. Datum Konflikt Gruppe fällt mit einer der Gruppen ausgewählte Termine des Turniers (Titel oben). Veröffentlichung der Liste der Konfliktgruppen soll nur um die Teilnehmer zu informieren.',
        'Коротко' : 'Kurz',
        'Ла: ' : 'La:',
        'Макс.' : 'Max.',
        'Международный' : 'International',
        'Мужской' : 'Männlich',
        'На главную' : 'Zuhause',
        'Нажмите на ссылку (») в колонке "Группы" для просмотра списка групп турнира, в которых зарегистрирована пара (участник).' : 'Klicken Sie auf den link (») in der spalte "Gruppen", um die liste des turniers, in dem das Paar registriert (Mitglied) anzuzeigen.',
        'Нажмите на ссылку в колонке "Группы" для просмотра списка групп турнира, в которых зарегистрирована пара (участник).' : 'Klicken Sie auf den link in der spalte "Gruppen", um die Liste des Turniers, in dem das Paar registriert (Mitglied) anzuzeigen.',
        'Назад' : 'Zurück',
        'Название' : 'Titel',
        'Нашли ошибку в работе системы? Что-то не нравится? Пожалуйста, напишите нам Ваши замечания и предложения.' : 'Sie einen Fehler gefunden im system? Etwas nicht gefällt? Mailen sie uns Ihre kommentare und vorschläge bitte.',
        'Не оплачено' : 'Nicht bezahlt',
        'Нет доступных групп.' : 'Keine gruppen zur verfügung.',
        'Номер WDSF' : 'Numero WDSF',
        'Номер партнера' : 'Numero männer',
        'Номер партнерши' : 'Numero frau',
        'Номер ФТСАРР' : 'Numero RFDARR',
        'Номера классификационных книжек WDSF' : 'Nicht einstufung der bücher WDSF',
        'Номера классификационных книжек ФТСАРР' : 'Nicht Einstufung Bücher RFDARR',
        'Обзор' : 'Überblick',
        'Обратная связь' : 'Feedback',
        'Оплатить на danceplat.ru' : 'Zahlen Sie danceplat.ru',
        'Оплачено': 'Bezahlt',
        'Организатор' : 'Veranstalter',
        'Оставьте свои отзывы, предложения, замечания!':'Geben sie uns ihr feedback, anregungen, kommentare!',
        'Открыть для просмотра' : 'Einen blick',
        'Открыть список групп' : 'Sehen sie sich eine liste der gruppen',
        'Открыть список групп, в которых зарегистрирована пара' : 'Sehen sie sich eine liste von gruppen, in denen das paar registriert',
        'Открыть список участников' : 'Sehen sie sich eine liste der teilnehmer',
        'Открыть список участников группы' : 'Sehen sie sich eine liste der gruppenmitglieder',
        'Отмена' : 'Stornierung',
        'Отображать дополнительные столбцы' : 'Zeigen sie zusätzliche spalten',
        'Отправить' : 'Senden',
        'Оформить »' : 'Inhalt »',
        'Оформить регистрацию' : 'Machen anmeldung',
        'Очистить' : 'Reinigen',
        'Пара' : 'Paar',
        'Партнер / Партнерша' : 'Männer / Frauen',
        'Партнер / партнерша' : 'Männer / Frauen',
        'Партнер' : 'Männer',
        'Партнерша' : 'Frauen',
        'Первая страница' : 'Startseite',
        'Передать данные' : 'Übertragen von daten',
        'Перейти к списку групп пары / участника (' : 'Zurück zur liste gruppen paare / teilnehmer (',
        'Подтверждение регистрационных данных' : 'Bestätigung der registrierungsdaten',
        'Поиск' : 'Suche',
        'Поиск в столбце': 'Suchen spalte',
        'Показать ошибки' : 'Fehler anzeigen',
        'Пол' : 'Geschlecht',
        'Поля отмеченные * обязательны для заполнения.' : 'Mit * gekennzeichnete felder sind pflichtfelder.',
        'После завершения регистрации произойдет передача данных в danceplat.ru, по прошествии некоторого времени после завершения оплаты ваши данные отобразятся в регистрационных списках.' : 'Nach abschluss der registrierung der datenübertragung auftreten danceplat.ru, für einige zeit nach dem abschluss ihrer zahlungsdaten in den meldelisten angezeigt.',
        'После завершения регистрации произойдет переход на страницу с группами пары, там вы сможете выбрать необходимые группы и перейти к оплате.' : 'Nach abschluss der registrierung der datenübertragung auftreten danceplat.ru, für einige zeit nach dem abschluss ihrer zahlungsdaten in den meldelisten angezeigt',
        'Последнее обновление спортсменов ФТСАРР было' : 'Letztes update war RFDARR athleten',
        'Последняя страница' : 'Letzte seite',
        'Лимит' : 'Limit',
        'Предыдущая страница' : 'Vorherige seite',
        'Программа' : 'Programm',
        'Просмотр формы' : 'Formularvorschau',
        'Размер страницы':'Seitengröße',
        'Ранг' : 'Rang',
        'Регистрация' : 'Registrierung',
        'Регистрация WDSF' : 'Registrierung WDSF',
        'Регистрация других участников' : 'Registrierung sie mit anderen mitgliedern',
        'Регистрация осуществляется по WDSF номерам. Поиск участников идет по базе данных "World DanceSport Federation".' : 'Registrierung wird von WDSF-Nummer. Mitgliederbörse ist auf datenbank "World Dancesport Federation".',
        'Регистрация осуществляется по номерам классификационных книжек и на основании информации Базы данных спортсменов "Союза танцевального спорта России" на момент регистрации.' : 'Die Anmeldung erfolgt durch Zahlen und Klassifizierung der Bücher auf der Grundlage der Informationen vorgenommen, Datenbanken Athleten Union Dancesport Russland bei der Registrierung.',
        'Регистрация прошла успешно, на данной странице отображены все группы пары/участника в турнире.': 'Die registrierung ist erfolgreich, zeigt dieser seite alle paare gruppen / teilnehmer im turnier.',
        'Регистрация ФТСАРР' : 'Registrierung RFDARR',
        'Регистрация участников »' : 'Registrierung der Teilnehmer »',
        'Регистрация участников на турнир' : 'Registrierung für das turnier',
        'Регистрация участников невозможна! Статус турнира - "': 'Registrierung der teilnehmer ist nicht möglich! Cupstatus - "',
        'Регистрация участников по WDSF номерам' : 'Registrierung der teilnehmer an WDSF-Nummern',
        'Регистрация участников по ФТСАРР номерам' : 'Registrierung der teilnehmer an RFDARR-Nummern',
        'Редактирование группы' : 'Bearbeiten einer gruppe',
        'Редактирование турнира' : 'Bearbeiten turnier',
        'Режим' : 'Modus',
        'Серый цвет' : 'Grau',
        'Система регистрации' : 'Aufnahmesystem',
        'Скрывать дополнительные столбцы' : 'Zusätzliche spalten ausblenden',
        'Соло' : 'Solo',
        'Сообщение' : 'Nachricht',
        'Сохранить' : 'Sparen',
        'Список всех групп турнира' : 'Liste aller gruppen des turniers',
        'Список всех уникальных участников турнира' : 'Liste aller einzigartige turnierteilnehmer',
        'Список всех участников »' : 'Liste aller teilnehmer »',
        'Спортсменов WDSF в БД' : 'WDSF-Athleten in DB',
        'Спортсменов в БД' : 'Athleten in DB',
        'Спортсменов ФТСАРР в БД' : 'RFDARR-Athleten in DB',
        'Справочники' : 'Verzeichnisse',
        'Ст: ' : 'St:',
        'Статистика' : 'Statistiken',
        'Статус' : 'Status',
        'Страна' : 'Land',
        'Страница' : 'Seite',
        'Тема сообщения' : 'Vorbehaltlich ',
        'Тип' : 'Typ ',
        'Тренер #1. Фамилия, Имя' : 'Coach Nr. 1. Nachname',
        'Тренер #2. Фамилия, Имя' : 'Coach Nr. 2. Nachname',
        'Тренер(ы)' : 'Trainer',
        'Тренеры' : 'Trainer ',
        'Турнир' : 'Turnier ',
        'Турниры' : 'Turniere ',
        'Удалить' : 'Entfernen',
        'Уникальные участники турнира, всего ':'Einzigartige teilnehmer im turnier, nur',
        'Участник' : 'Party',
        'Участники' : 'Die teilnehmer',
        'Участники группы' : 'Gruppenmitglieder',
        'Участники ФТСАРР' : 'Teilnehmer RFDARR',
        'Фамилия' : 'Nachname',
        'Фамилия, Имя' : 'Nachname, Vorname',
        'Фильтр: Ранг турнира' : 'Filter: Rang turnier',
        'Фильтр: Статус турнира' : 'Filter: Wettbewerbsstatus',
        'Форма обратной связи' : 'Feedback-formular',
        'Хеш' : 'Hasch',
        'Цена' : 'Preis',
        'руб.':'rub.',
        'Часть данных получена от WDSF.' : 'Ein teil der von der WDSF erhaltenen daten.',
        'Черный цвет - участие в группе оплачено.' : 'Schwarz - die teilnahme an der gruppe bezahlt.',
        'Чтобы разблокировать вкладку нажмите ″Назад″' : 'Um die registerkarte entsperren, klicken sie auf "Zurück"',
        'ЧЧ:ММ' : 'SS:MM',
        'Щелчком мыши выберите группы, в которые необходимо зарегистрировать пару.' : 'Klicken Sie auf die gruppen, zu denen müssen sie paar registrieren auswählen.',
        'Щелчком мыши выберите необходимые группы для передачи данных в платежную систему.' : 'Klicken sie auf die gewünschte gruppe für die datenübertragung an das zahlungssystem auszuwählen.',
        'Язык' : 'Sprache',
        'Язык системы' : 'System sprache',
        'Ярким цветом выделены турниры, которые уже есть базе данных. Сравнение идет по IdInternal. Для сохранения турнира заполните все дополнительные поля в диалоговом окне импорта.' : 'Helle farbe zuordnet turnieren, die bereits eine datenbank ist. Der vergleich ist auf IdInternal. Um das turnier zu füllen sie alle zusätzlichen felder in der importdialog zu speichern.',
        
        'Задать вопрос' : 'Frage stellen',
        'Инструкция к регистрации' : 'Hinweise für die registrierung',
        'Информация о турнире' : 'Turnier-info',
        'Информация »' : 'Information »',
        
        
        /* 11 oct*/
        'Поиск регистрации' : 'Search registration',
        'Группа в турнире' : 'Competition',
        'Все группы •' : 'All competitions •',
        'Все группы »' : 'All competitions »',
        'Регистрация »' : 'Registration »',
        'Все участники »' : 'All participants »',
        'Все участники •' : 'All participants •',
        'Сейчас Вы на этой странице' : 'You are currently on this page',
        'Регистрация •' : 'Registration •',
        'Результаты регистрации' : 'Registration results',
        'Перейти к списку групп пары / участника для оплаты (' : 'Go to the list of competitions (couple / participant) for payment (',
        'Информация о регистрации в группу' : 'Information on registration in competition',
        'После завершения регистрации перейдите на страницу с группами пары / участника, там вы сможете выбрать необходимые группы и передать данные в платежную систему.' : 'Once registration is complete, go to the page with competitions of couples / participant, where you can select the required competitions and transmit data to the billing system.',
        'Статус пары' : 'Couple status',
        'Возрастная группа пары' : 'Couple age group',
        'Участники группы •' : 'Participants of competition •',
        'Группы участника •' : 'Competitions of participant •',
        'Группы пары •' : 'Competitions of couple •',
        'участника' : 'participant',
        'пары' : 'couple',
        'ФТСАРР' : 'RFDARR',
        'Перейти' : 'Watch',
        'Фамилия спортсмена' : 'Last name',
        'Вы можете найти все группы, в которых зарегистрирован спортсмен. Поиск по всем турнирам.' : 'You can find all competitions in which the registered athlete. Search All tournaments.',
        'Группы, в которых зарегистрирован спортсмен' : 'Competitions in which the registered athlete',
        'Импортировать' : 'Import',
        'Импортировать доступные' : 'Import available items',
        'Ссылка на источник данных:' : 'Link to source of data',
        'Группа' : 'Competition',
        'Возр. гр.' : 'Age group',
        'Выберите дату для активации переключателя' : 'Select date for activate switcher',
        'Дисциплина' : 'Discipline',
        'Соответствующая группа WDSF' : 'Competition WDSF',
        
        ' - участие не оплачено.' : ' - participation is not paid.',
        ' - участие отменено.' : ' - participation is canceled.',
        'Оплачены' : 'Paid',
        'd MMMM' : 'd MMMM',
        'WDSF Controller' : 'WDSF Controller',
        'Возр. группа' : 'Age group',
        'Выберите организатора для доступа к регистрации:' : 'Select an organizer for access to registration:',
        'Группы »' : 'Competitions »',
        'Группы •' : 'Competitions •',
        'Код доступа не найден, переход на страницу для регистрации невозможен.' : 'The access code is not found, a transition to the page for registration is impossible.',
        'Количество оплативших участников' : 'Number of paid participants',
        'Количество оплаченных групп' : 'Number of paid competitions',
        'Нет данных.' : 'No data.',
        'Поиск регистрации участника по фамилии!' : 'Searching registration of athlete by surname',
        'Список всех участников турнира' : 'List of participants of the tournament',
        'Уникальные участники турнира' : 'Unique participants of the tournament',
        'Участники »' : 'Participants »',
        'Участники •' : 'Participants •',
        'Экспорт участников »' : 'Export participants',
        'Перейдите по ссылке для получения подробной информации' : 'Klicken Sie hier für weitere Informationen',
        'ВАЖНОЕ ОБЪЯВЛЕНИЕ' : 'Wichtige mitteilung',
        'Зарегистрировать ещё участников »' : 'Registrieren Sie sich mehr Teilnehmer »',
        'Введите номера классификационных книжек ФТСАРР' : 'Geben Sie die Nummer Einstufung Bücher RFDARR',
        'Введите номера классификационных книжек WDSF' : 'Geben Sie die Nummer Einstufung Bücher WDSF',
        'Регистрация осуществляется по MIN номерам WDSF. Поиск участников идет по базе данных "World DanceSport Federation".' : 'Die Anmeldung erfolgt durch MIN Zahlen WDSF getan. Suche Mitglieder ist die Datenbank "World Dance Sport Federation"',
        'Тренер. Фамилия, Имя' : 'Coach. Nachname Vorname',
        'Оплачено участников' : 'Paid participants',
        'Регистрация в турнир завершена. Все платежи запрещены.' : 'Registration in the tournament is completed. All payments are prohibited.',
        'Для всех номинаций кроме \"соло\", стоимость участия указана для пары участников.' : 'For all nominations except \"solo\", the price of participation is for couple of participants.',
        'Для всех номинаций стоимость участия указана для пары участников.' : 'For all competitions price is for couple of participants.',
        'Доступные группы.' : 'Available competitions.',
        'Доп. поля можно не заполнять.' : 'Other fields may be empty.',
    '-- Вкладка по умолчанию --' : '-- Default tab page --',
    'Другие' : 'Others',
    '-- Язык по умолчанию --' : '-- Default language --',
    'Количество доступных мест' : 'The number of tickets available for the participants',
    'Для некоторых групп могут быть введены ограничения. "Доступно мест" это "Лимит" минус "Количество проданных билетов".' : 'Some competition may be restrictions. "Available" this "Limit" minus "Number of tickets sold."',
    'Группы, в которых не осталось мест(0) закрыты для регистрации и продажи билетов.' : 'Competitions in which there is no available tickets (0) closed to registration and ticket sales.',
    'Осталось мест' : 'Available',
    
    'Перейти на сайт ФТСАРР' : 'Go to RFDARR site',
    'Регистрация осуществляется по номерам классификационных книжек и на основании информации' : 'Registration is carried by numbers and classification of books based on the information',
    'Базы данных спортсменов "Союза танцевального спорта России"' : 'Databases athletes "Union DanceSport of Russia"',
    'на момент регистрации.' : 'at the time of registration.',
    'Выберите номинации' : 'Select competitions',
    'Класс ST, LA' : 'ST, LA class',
    'Регистрация закрыта':'Registration is closed'

  },
  toItalian: {
    'Оплата отключена' : 'Il pagamento è disattivato',
    'Зарегистрировать ещё группы': 'Registrati altro gruppo',
    'Регистрация выполнена.': 'La registrazione è completa.',
    'Регистрация не выполнена.': 'Registrazione fallita.',
    'Обнаружены конфликтные группы для участника' : 'Gruppi in conflitto trovati al partito',
    'Место проведения':'Sede',
    'Размер страницы' : 'Dimensioni pagina',
    'Поиск в столбце' : 'Cerca nella colonna',
    'Все группы' : 'Tutti i gruppi',
    'Внимание!' : 'Attenzione Prego!',
    'Готово!' : 'Fatto!',
    'Язык системы' : 'Lingua del sistema',
    'd MMMM y' : 'd MMMM y',
    'В списке не отображены группы, в которых данная пара уже зарегистрирована.' : 'L\'elenco non è visualizzato gruppi in cui questa coppia è già registrato.',
    'Ваш email' : 'La tua email',
    'Ваше имя' : 'Il tuo nome',
    'Веб-сайт организатора' : 'Il sito web dell\'organizzatore',
    'Возрастная группа' : 'Fascia d\'età',
    'Возрастные группы' : 'Classi di età',
    'Время' : 'PERIODO DI',
    'Все дни' : 'Tutti i giorni',
    'Всего групп' : 'Tutti i gruppi',
    'Всего участников / уникальных' : 'Numero di partecipanti / unica',
    'Вход' : 'Ingresso',
    'Выберите группы!' : 'Selezionare il gruppo!',
    'Выберите турнир для отображения подробной информации.' : 'Scegli il torneo per visualizzare le informazioni dettagliate.',
    'Выбрано' : 'Congiunto',
    'Главный тренер' : 'Capo allenatore',
    'Город' : 'Una Città',
    'Город, Страна' : 'Città, Paese',
    'групп из' : 'gruppi di',
    'Группы' : 'Gruppi',
    'Группы пары' : 'Gruppo coppia',
    'Группы участника' : 'Gruppi di utenti',
    'Далее' : 'Più Avanti',
    'Дата' : 'La Data',
    'Дата начала / окончания' : 'Data inizio / fine',
    'Дата начала' : 'Data di inizio',
    'Дата окончания' : 'Data di scadenza',
    'Дата рождения' : 'Data di nascita',
    'Детально' : 'Nel dettaglio',
    'Программа' : 'Programma',

    'Для просмотра списка всех групп турнира нажмите на ссылку (») в колонке "Группы" или выберите внизу вкладку "Группы(N)".' : 
    'Per visualizzare l\'elenco di tutti i gruppi del torneo cliccare sul link (») in "gruppi" scheda nella parte inferiore, oppure selezionare "Gruppi(N)".',

    'Для просмотра списка всех участников турнира нажмите на ссылку (») в колонке "Участники".' : 
    'Per visualizzare un elenco di tutti i partecipanti del torneo cliccare sul link (») nella sezione "Partecipanti".',

    'Для просмотра списка участников группы нажмите на ссылку (») в колонке "Участники".' : 
    'Per un elenco dei membri del gruppo, fare clic sul link (») nella sezione "Partecipanti".',

    'Для регистрации в "соло" заполните только одно поле.' : 
    'Per iscriversi al "solo" riempire un solo campo.',

    'Для регистрации в турнире нажмите на ссылку (») в колонке "Регистрация".' : 
    'Per iscriversi al torneo cliccare sul link (») nel "Registro".',

    'Для регистрации в "соло" нажмите на переключатель.' : 
    'Per registrarti per la stampa "solo" l\'interruttore.',

    'Добавить' : 'Aggiungere',
    'Дополнительная информация' : 'Maggiori informazioni',
    'Другие тренеры' : 'Altri allenatori',
    'Женский' : 'Femminile',
    'Зарегистрировать' : 'Libro',
    'Идет загрузка групп...' : 'Caricamento gruppi ...',
    'Идет загрузка данных...' : 'Caricamento dei dati ...',
    'из' : 'dal',
    'Изменить' : 'Cambiare',
    'Импорт' : 'Importazioni',
    'Имя' : 'Nome',
    'Информация' : 'Informazioni',
    'Класс' : 'La Classe',
    'Классы' : 'Classi',
    'Клуб / Город' : 'Club / Città',
    'Клуб' : 'Club',
    'Конфликтные группы для ' : 'Gruppi in conflitto a',

    'Конфликтные группы участника - это группы из других турниров, в которых зарегистрирован участник. Дата конфликтной группы совпадает с одной из дат групп выбранного турнира (заголовок сверху). Публикация списка конфликтных групп предназначена лишь для информирования участников.' : 
    'Gruppi di utenti in conflitto - un gruppo di altri tornei, in cui il partecipante è registrato. Data di gruppi in conflitto coincide con uno dei gruppi selezionati date del torneo (titolo di cui sopra). Pubblicare un elenco di gruppi in conflitto hanno il solo scopo di informare i partecipanti.',

    'Коротко' : 'Breve',
    'Ла: ' : 'La: ',
    'Мужской' : 'Uomo',
    'Нажмите на ссылку в колонке "Группы" для просмотра списка групп турнира, в которых зарегистрирована пара (участник).' : 
    'Clicca sul link nella sezione "Gruppi" per visualizzare l\'elenco del torneo, in cui la coppia è registrata (membro).',

    'Назад' : 'Fa',
    'Название' : 'Il Nome',
    'Нашли ошибку в работе системы? Что-то не нравится? Пожалуйста, напишите нам Ваши замечания и предложения.' : 'Trovato un bug nel sistema? Qualcosa non va? Vi preghiamo di inviarci i vostri commenti e suggerimenti.',
    'Не оплачено' : 'Non pagato',
    'Нет доступных групп.' : 'Non ci sono gruppi.',
    'Номер WDSF' : 'Numero WDSF',
    'Номер партнера' : 'Numero Partner',
    'Номер партнерши' : 'Partner Number',
    'Номер ФТСАРР' : 'Numero STSR',
    'Номера классификационных книжек WDSF' : 'Non classificazione dei libri WDSF',
    'Номера классификационных книжек ФТСАРР' : 'Non classificazione dei libri STSR',
    'Обратная связь' : 'Retroazione',
    'Оплатить на danceplat.ru' : 'Pagare per danceplat.ru',
    'Организатор' : 'Organizzatore',
    'Открыть для просмотра' : 'Aperto per la visualizzazione',
    'Открыть список групп' : 'Visualizzare un elenco di gruppi',
    'Открыть список групп, в которых зарегистрирована пара' : 'Visualizzare un elenco di gruppi in cui la coppia è registrato',
    'Открыть список участников' : 'Visualizzare un elenco di partecipanti',
    'Открыть список участников группы' : 'Guarda l\'elenco dei membri del gruppo',
    'Отмена' : 'Cancellazione',
    'Отображать дополнительные столбцы' : 'Visualizzare colonne aggiuntive',
    'Отправить' : 'Inviare',
    'Оформить »' : 'Contenuti »',
    'Оформить регистрацию' : 'Contenuti registrazione',
    'Очистить' : 'Pulito',
    'Пара' : 'La Coppia',
    'Партнер / Партнерша' : 'Male / Female',
    'Партнер' : 'Male',
    'Партнерша' : 'Female',
    'Первая страница' : 'Prima pagina',
    'Перейти к списку групп пары / участника (' : 'Torna alla lista dei gruppi coppie / attore (',
    'Подтверждение регистрационных данных' : 'La conferma dei dati di registrazione',
    'Поиск' : 'Ricerca',
    'Пол' : 'Paul',
    'Поля отмеченные * обязательны для заполнения.' : 'I campi contrassegnati con * sono obbligatori.',
    'После завершения регистрации произойдет передача данных в danceplat.ru, по прошествии некоторого времени после завершения оплаты ваши данные отобразятся в регистрационных списках.' : 'Dopo aver completato la registrazione trasferirà danceplat.ru dati, dopo qualche tempo dopo il pagamento dei vostri dati è visualizzata in elenchi di registrazione.',
    'После завершения регистрации произойдет переход на страницу с группами пары, там вы сможете выбрать необходимые группы и перейти к оплате.' : 'Dopo la registrazione è completa, si muove alla pagina con i gruppi coppia, non ci è possibile selezionare il gruppo desiderato e andare al pagamento.',
    'Последняя страница' : 'Ultima pagina',
    'Предыдущая страница' : 'Pagina precedente',
    'Ранг' : 'Rango',
    'Регистрация' : 'Check In',
    'Регистрация WDSF' : 'Registrati WDSF',
    'Регистрация других участников' : 'Registrazione di altri partecipanti',
    'Регистрация осуществляется по WDSF номерам. Поиск участников идет по базе данных "World DanceSport Federation".' : 'La registrazione è fatto da numeri WDSF. Cerca Utenti è il database "World DanceSport Federazione".',
    'Регистрация осуществляется по номерам классификационных книжек и на основании информации Базы данных спортсменов "Союза танцевального спорта России" на момент регистрации.' : 'La registrazione è effettuata dal numero di libri e di classificazione in base alle informazioni Banche dati degli atleti dell\' Unione DanceSport Russia "al momento della registrazione.',
    'Регистрация ФТСАРР' : 'Registrati STSR',
    'Регистрация участников »' : 'Registrazione dei partecipanti "',
    'Регистрация участников на турнир' : 'L\'iscrizione al torneo',
    'Регистрация участников по WDSF номерам' : 'Registrazione dei partecipanti ai numeri WDSF',
    'Регистрация участников по ФТСАРР номерам' : 'Registrazione dei partecipanti per i numeri STSR',
    'Режим' : 'Modo',
    'Система регистрации' : 'Sistema di registrazione',
    'Скрывать дополнительные столбцы' : 'Nascondi colonne aggiuntive',
    'Следующая страника' : 'Successivo stranika',
    'Соло' : 'Assolo',
    'Сообщение' : 'Il Messaggio',
    'Список всех групп турнира' : 'Vedi tutti i gruppi del torneo',
    'Список всех уникальных участников турнира' : 'Elenco di tutti i partecipanti al torneo unici',
    'Список всех участников »' : 'Elenco di tutti i partecipanti "',
    'Справочники' : 'Riferimento',
    'Ст: ' : 'St: ',
    'Статус' : 'Lo stato',
    'Страна' : 'Paese',
    'Страница' : 'La Pagina',
    'Тема сообщения' : 'Soggetto del messaggio',
    'Тип' : 'Tipo Di',
    'Тренер #1. Фамилия, Имя' : 'Coach # 1. Cognome Nome',
    'Тренер #2. Фамилия, Имя' : 'Coach # 2. Cognome Nome',
    'Тренер(ы)' : 'L\'allenatore (s)',
    'Тренеры' : 'Formatori',
    'Турнир' : 'Torneo',
    'Турниры' : 'Tornei',
    'Удалить' : 'Rimuovere',
    'Участник' : 'Partito',
    'Участники' : 'Partecipanti',
    'Участники ФТСАРР' : 'Partecipanti STSR',
    'Фамилия' : 'Cognome',
    'Фамилия, Имя' : 'Cognome Nome',
    'Фильтр: Ранг турнира' : 'Filtro: Classifica torneo',
    'Фильтр: Статус турнира' : 'Ordina per: Titolo Tournament',
    'Форма обратной связи' : 'Modulo di feedback',
    'Цена' : 'Price',
    'руб.':'rub.',
    'Щелчком мыши выберите группы, в которые необходимо зарегистрировать пару.' : 'Fare clic per selezionare il gruppo a cui si desidera registrare coppia.',
    'Щелчком мыши выберите необходимые группы для передачи данных в платежную систему.' : 'Fare clic per selezionare la banda desiderata per trasmettere i dati al sistema di pagamento.',
    'Язык' : 'La Lingua',
    ' - участие в группе не оплачено.' : ' - La partecipazione al gruppo non viene pagato.',
    ' - участие в группе отменено.' : ' - Partecipazione al gruppo annullata.',
    'Cписок всех групп »' : 'Elencare tutti i gruppi »',
    'Выберите год и турнир. Ярким синим цветом выделены группы, которые уже есть базе данных. Сравнение идет по IdInternal. Красным выделены группы с ошибками, их можно исправить.' : 'Selezionare l\'anno e il torneo. Luminosi gruppi isolati blu che già dispongono di un database. Il confronto è a IdInternal. Gruppo di colore rosso con errori possono essere corretti.',
    'Выход' : 'Produzione',
    'Год' : 'Anno',
    'Группы, доступные для импорта' : 'Gruppi disponibili per l\'importazione',
    'Доступные для импорта турниры' : 'Disponibile per i tornei importazioni',
    'Заголовок' : 'Titolo',
    'Загрузка групп в турнир' : 'Gruppi Caricamento nel torneo',
    'Макс.' : 'Max.',
    'Международный' : 'Internazionale',
    'Нажмите на ссылку (») в колонке "Группы" для просмотра списка групп турнира, в которых зарегистрирована пара (участник).' : 'Clicca sul link (») nella sezione" Gruppi "per visualizzare l\'elenco del torneo, in cui la coppia è registrata (membro).',
    'Партнер / партнерша' : 'Partner / Partner',
    'Показать ошибки' : 'Mostra errori',
    'Лимит' : 'Limite',
    'Просмотр формы' : 'View forma',
    'Редактирование группы' : 'Gruppo Modifica',
    'Редактирование турнира' : 'Editing torneo',
    'Серый цвет' : 'Colore grigio',
    'Сохранить' : 'Salva',
    'Участники группы' : 'I membri della band',
    'Хеш' : 'Hash',
    'ЧЧ:ММ' : 'HH: MM',
    'Ярким цветом выделены турниры, которые уже есть базе данных. Сравнение идет по IdInternal. Для сохранения турнира заполните все дополнительные поля в диалоговом окне импорта.' : 'Il colore luminoso evidenziato tornei, che già dispongono di un database. Il confronto è a IdInternal. Per salvare il torneo di riempimento in tutti i campi aggiuntivi nella finestra di dialogo Importa.',
    'Доступные группы для регистрации.' : 'Gruppi disponibili per la registrazione.',
    'Выбрано %1 из %2.' : '% Selezionato 1% 2.',
    'Чтобы разблокировать вкладку нажмите ″Назад″' : 'Per sbloccare la scheda, fare clic su "Back"',
    'Заполните / измените остальные поля.' : 'Riempire / modificare gli altri campi.',
    'Вернуться назад' : 'Ritorno',
    'Данные для передачи в платежную систему' : 'I dati per la trasmissione al sistema di fatturazione',
    'На главную' : 'Casa',
    'Передать данные' : 'Dati Transfer',
    'Оставьте свои отзывы, предложения, замечания!' : 'Inviateci i vostri commenti, suggerimenti, commenti!',
    'Регистрация участников невозможна! Статус турнира - "' : 'Registrazione dei partecipanti non è possibile! Stato del torneo - "',
    'Группы турнира' : 'Gruppi di torneo',
    'Часть данных получена от WDSF.' : 'Parte dei dati ottenuti dal WDSF.',
    'Оплачено' : 'Pagato',
    'Черный цвет - участие в группе оплачено.' : 'Nero - partecipazione al gruppo pagato.',
    'Уникальные участники турнира, всего ' : 'Partecipanti unici nel torneo, unico',
    'Регистрация прошла успешно, на данной странице отображены все группы пары/участника в турнире.' : 'Registrazione avuto successo in questa pagina vengono visualizzati tutti i gruppi coppie / partecipante al torneo.',
    'Загрузить' : 'Scarica',
    'Обзор' : 'Recensione',
    'Выберите файл' : 'Scegli Il File',
    'Статистика' : 'Statistica',
    'Спортсменов в БД' : 'Atleti nel database',
    'Спортсменов ФТСАРР в БД' : 'Atleti STSR nel database',
    'Спортсменов WDSF в БД' : 'Atleti WDSF nel database',
    'Других спортсменов в БД' : 'Altri atleti nel database',
    'Последнее обновление спортсменов ФТСАРР было' : 'Ultimo aggiornamento era atleti STSR',
    'Доступен ФТСАРР' : 'Disponibile STSR',
    'Доступен WDSF' : 'Disponibile WDSF',
    'Доступен другим' : 'Disponibile ad altri',
    'Поиск регистрации' : 'Ricerca registrazione',
    'Группа в турнире' : 'Gruppo nel torneo',
    'Все группы •' : '• Tutti i gruppi',
    'Все группы »' : 'Tutti i gruppi »',
    'Регистрация »' : 'Registrati »',
    'Все участники »' : 'Tutti i partecipanti "',
    'Все участники •' : '• Tutti i partecipanti',
    'Сейчас Вы на этой странице' : 'Attualmente sei su questa pagina',
    'Регистрация •' : '• Register',
    'Результаты регистрации' : 'Risultati di registrazione',
    'Перейти к списку групп пары / участника для оплаты (' : 'Torna alla lista dei gruppi coppie / partecipante a pagare (',
    'Информация о регистрации в группу' : 'Check-in di gruppo Informazioni',
    'После завершения регистрации перейдите на страницу с группами пары / участника, там вы сможете выбрать необходимые группы и передать данные в платежную систему.' : 'Una volta completata la registrazione, andare alla pagina con un paio di gruppi / partito, dove è possibile selezionare il gruppo desiderato e trasmettere i dati al sistema di fatturazione.',
    'Статус пары' : 'Stato della coppia',
    'Возрастная группа пары' : 'Gruppo coppia Age',
    'Участники группы •' : '• Membri del Gruppo',
    'Группы участника •' : '• gruppi di utenti',
    'Группы пары •' : '• Gruppi coppie',
    'участника' : 'Membro',
    'пары' : 'vapore',
    'ФТСАРР' : 'STSR',
    'Перейти' : 'Andare',
    'Фамилия спортсмена' : 'Atleta Cognome',
    'Вы можете найти все группы, в которых зарегистрирован спортсмен. Поиск по всем турнирам.' : 'Potete trovare tutti i gruppi in cui l\'atleta è stato registrato. Cerca in tutti i tornei.',
    'Группы, в которых зарегистрирован спортсмен' : 'Gruppi in cui l\'atleta è registrato',
    'Импортировать' : 'Importazione',
    'Импортировать доступные' : 'Import disponibile',
    'Ссылка на источник данных:' : 'Link alla fonte dei dati: ',
    'Группа' : 'Gruppo',
    'Возр. гр.' : 'Crescente. c.',
    'Выберите дату для активации переключателя' : 'Selezionare una data per attivare l\'interruttore',
    'Дисциплина' : 'Disciplina',
    'Соответствующая группа WDSF' : 'Il corrispondente WDSF gruppo',
    ' - участие не оплачено.' : ' - La partecipazione non è pagato.',
    ' - участие отменено.' : ' - Partecipazione annullato.',
    'Оплачены' : 'Pagato',
    'd MMMM' : 'd MMMM',
    'WDSF Controller' : 'WDSF controller',
    'Возр. группа' : 'Crescente. gruppo',
    'Выберите организатора для доступа к регистрации:' : 'Selezionare organizzatore per l\'accesso alla registrazione: ',
    'Группы »' : 'Gruppi »',
    'Группы •' : 'Gruppi •',
    'Код доступа не найден, переход на страницу для регистрации невозможен.' : 'Il codice di accesso viene trovato, una transizione verso la pagina per la registrazione è impossibile.',
    'Количество оплативших участников' : 'Il numero di partecipanti pagati',
    'Количество оплаченных групп' : 'Numero di gruppi pagati',
    'Нет данных.' : 'Nessun dato.',
    'Поиск регистрации участника по фамилии!' : 'Ricerca per il nome della registrazione utente!',
    'Список всех участников турнира' : 'Elenco di tutti i partecipanti al torneo',
    'Уникальные участники турнира' : 'I partecipanti al torneo unici',
    'Участники »' : 'Partecipanti »',
    'Участники •' : 'Partecipanti •',
    'Экспорт участников »' : 'Partecipanti Export »',
    'Всего участников' : 'Numero di partecipanti',
    'уникальных' : 'unico',
    'Всего' : 'Solo',
    'Задать вопрос' : 'Fai una domanda',
    'Инструкция к регистрации' : 'Guida alla registrazione',
    'Информация о турнире' : 'Info Tournament',
    'Информация »' : 'Informazioni »',
    'Перейдите по ссылке для получения подробной информации' : 'Clicca qui per maggiori informazioni',
    'ВАЖНОЕ ОБЪЯВЛЕНИЕ' : 'ANNUNCIO IMPORTANTE',
    'Зарегистрировать ещё участников »' : 'Registrazione più membri »',

     
    'Введите номера классификационных книжек ФТСАРР' : 'Inserire il numero di libri di classificazione RFDARR',
    'Введите номера классификационных книжек WDSF' : 'Inserire il numero di libri di classificazione WDSF',
    
    'Регистрация осуществляется по MIN номерам WDSF. Поиск участников идет по базе данных "World DanceSport Federation".' : 
    'La registrazione è effettuata in base al numero VIN WDSF. Cerca Utenti è il database "World DanceSport Federazione".',
    
    'Тренер. Фамилия, Имя' : 'Coach',
    'Оплачено участников' : 'Partecipanti a pagamento',
    'Регистрация в турнир завершена. Все платежи запрещены.' : 'L\'iscrizione al torneo è completato. Tutti i pagamenti sono vietati.',
    'Для всех номинаций кроме \"соло\", стоимость участия указана для пары участников.' : 'Per tutte le candidature, eccetto \"solo\", il costo di partecipazione è per le coppie di partecipanti.',
    'Для всех номинаций стоимость участия указана для пары участников.' : 'Per tutta la tassa di candidature di partecipazione è per le coppie di partecipanti.',
    'Доступные группы.' : 'Gruppi disponibili.',
    'Доп. поля можно не заполнять.' : 'Extra. i campi sono facoltativi.',
    '-- Вкладка по умолчанию --' : '-- La scheda predefinita --',
    'Другие' : 'Gli altri',
    '-- Язык по умолчанию --' : '-- Lingua di Default --',
    'Количество доступных мест' : 'Il numero di posti disponibili',
    
    'Для некоторых групп могут быть введены ограничения. "Доступно мест" это "Лимит" минус "Количество проданных билетов".' : 
    'Alcuni gruppi potrebbero essere restrizioni. "Luogo accessibile" che "limite" meno "il numero di biglietti venduti."',
    
    'Группы, в которых не осталось мест(0) закрыты для регистрации и продажи билетов.' : 
    'Gruppi in cui non c\'è spazio (0) chiuso per registrazione e vendita dei biglietti.',
    
    'Осталось мест' : 'Luoghi sinistra',
    'Перейти на сайт ФТСАРР' : 'Go to RFDARR site',
    'Регистрация осуществляется по номерам классификационных книжек и на основании информации' : 'Registration is carried by numbers and classification of books based on the information',
    'Базы данных спортсменов "Союза танцевального спорта России"' : 'Databases athletes "Union DanceSport of Russia"',
    'на момент регистрации.' : 'at the time of registration.',
    'Выберите номинации' : 'Select competitions',
    'Класс ST, LA' : 'ST, LA class',
    'Регистрация закрыта':'Registration is closed' 
  },
  getTranslate: function(word, toLanguage){
    var def = function(key){
        //console.log("'" + key + "' : '',");
        
        return key; 
    };  
     
          
    switch(toLanguage){
        case 'en':
            return this.toEnglish[word] ? this.toEnglish[word] : def(word);
        case 'de':
            return this.toDeutsch[word] ? this.toDeutsch[word] : def(word);
        case 'it':
            return this.toItalian[word] ? this.toItalian[word] : def(word);
    }
    
    return word;
  }
});
