controllers/MainCtrl.js    
controllers/TournamentCtrl.js
controllers/TournamentsCtrl.js
controllers/TournamentCompetitionsCtrl.js
controllers/TournamentParticipantsCtrl.js
controllers/SearchParticipantsCtrl.js
controllers/RegistrationCtrl.js
controllers/PaymentCtrl.js
controllers/CompetitionCtrl.js
controllers/CompetitionParticipantsCtrl.js
controllers/AgeCategoriesCtrl.js
controllers/ImportTournamentsCtrl.js
controllers/ImportCompetitionsCtrl.js
controllers/ImportPersonsCtrl.js
controllers/FeedBackCtrl.js
services/RESTSrvc.js
services/TournamentSrvc.js
services/TournamentRankSrvc.js
services/TournamentStatusSrvc.js   
services/CompetitionSrvc.js
services/CoupleSrvc.js
services/PersonSrvc.js
services/DisciplineSrvc.js
services/DancerClassSrvc.js
services/AgeCategorySrvc.js
services/ParticipantSrvc.js
services/OtherSrvc.js
services/ImportSrvc.js
services/FeedBackSrvc.js
services/LocationSrvc.js
services/RegistrationSrvc.js
services/ReportSrvc.js
services/UtilsSrvc.js
directives/stcalert.js
directives/stcgrid.js
directives/tournamentform.js
directives/competitionform.js
directives/danceplatUDSRPay.js
directives/danceplatOtherPay.js
localization/dict.js
localization/filter.js
filters/cacheDate.js